// ============================================================
// 国际化 / i18n — 中文 <-> English
// ============================================================

const I18N = {
  zh: {
    'site.title': '🏫 华联中学初二忠评语系统',
    'site.footer': '© 2026 华联中学 · Hua Lian High School · CHEW YEN HAN 制作',
    'lang.switch': 'English',

    'login.heading': '🏫 华联中学初二忠评语系统',
    'login.subtitle': '教师登录 / Teacher Login',
    'login.username': '账号 / Username',
    'login.password': '密码 / Password',
    'login.placeholder': '输入密码',
    'login.button': '登录 / Login',
    'login.error': '账号或密码错误',
    'login.reset_hint': '如需重置密码，请联系班主任',
    'login.select_account': '选择账号...',

    'report.title': '学生评语录入',
    'report.hello': '你好',
    'report.form_teacher': '(班主任)',
    'report.subjects_count': '个科目',
    'report.progress': '进度',
    'report.mark_complete': '✅ 标记全部完成',
    'report.logout': '🚪 登出',
    'report.col_no': 'No.',
    'report.col_photo': '照片',
    'report.col_name': '学生姓名 / Nama Murid',
    'report.col_group': '班',
    'report.col_feedback': '评语 / Maklum Balas',
    'report.col_status': '✅',
    'report.placeholder': '输入评语... / Sila masukkan maklum balas...',
    'report.no_students': '该科目暂无学生',
    'report.no_photo': '无照片',
    'report.loading': '加载中...',
    'report.load_failed': '加载失败',
    'report.saving': '保存中...',
    'report.saved': '已保存',
    'report.save_failed': '保存失败',
    'report.export_csv': '📥 导出 CSV',
    'report.confirm_complete': '确定将所有学生标记为完成？',
    'report.error_operation': '操作失败',

    'dashboard.title': '📊 班级评语总览',
    'dashboard.overall_pct': '总体完成率',
    'dashboard.overall_filled': '已填写 / 总计',
    'dashboard.subject_count': '科目总数',
    'dashboard.subjects_progress': '📋 各科目进度',
    'dashboard.matrix': '📊 全科矩阵',
    'dashboard.matrix_hint': '横向滚动查看全部科目',
    'dashboard.generate_links': '🔄 生成/刷新链接',
    'dashboard.links_hint': '生成后把链接发给对应家长。每人一个唯一链接，只能看到自己孩子的评语。',
    'dashboard.links_placeholder': '点击上方按钮生成链接',
    'dashboard.export_full': '📥 导出全科 CSV',
    'dashboard.export_per_student': '📥 按学生导出',
    'dashboard.enter_report': '📝 录入评语',
    'dashboard.loading': '加载中...',
    'dashboard.load_failed': '加载失败',
    'dashboard.teacher_col': '负责老师',
    'dashboard.student_col': '学生',
    'dashboard.completed': '完成',
    'dashboard.incomplete': '未完成',

    'parent.loading': '⏳ 加载报告...',
    'parent.title': '📋 学生成绩报告',
    'parent.subjects_count': '个科目',
    'parent.col_no': '#',
    'parent.col_subject': '科目 / Subjek',
    'parent.col_feedback': '老师评语 / Maklum Balas',
    'parent.col_status': '状态',
    'parent.complete': '✅ 完成',
    'parent.pending': '⏳ 待填写',
    'parent.no_feedback': '（暂无评语 / No feedback yet）',
    'parent.teacher_label': '老师',
    'parent.confidential': '⚠️ 此报告为机密文件，仅供家长或监护人查看。\nThis report is confidential. For parents/guardians only.\nGenerated by 华联中学初二忠评语系统 · Hua Lian High School J2Y Report System',
    'parent.error_title': '⚠️ 无法加载报告',
    'parent.error_hint': '请联系班主任获取正确的访问链接。\nPlease contact the class teacher for the correct access link.',
    'parent.no_code': '未提供访问码。请使用班主任提供的链接。\nNo access code provided. Please use the link from your class teacher.',
    'parent.print': '🖨️ 打印 / Print',

    'group.J2Y': '初二忠',
    'group.J2Y_name': 'J2Y 初二忠',

    'teacher.form_teacher': '👑 班主任',
    'teacher.chinese_t': '📖 华文老师', 'teacher.malay_t': '📖 国文老师',
    'teacher.english_t': '📖 英文老师', 'teacher.math_t': '🔢 数学老师',
    'teacher.science_t': '🔬 科学老师', 'teacher.geography_t': '🌏 地理老师',
    'teacher.history_t': '📜 历史老师', 'teacher.computer_t': '💻 电脑老师',
    'teacher.pe_t': '🏃 体育老师', 'teacher.robotics_t': '🤖 机器人老师',
    'teacher.art_t': '🎨 美术老师',
  },

  en: {
    'site.title': '🏫 Hua Lian High School J2Y Report System',
    'site.footer': '© 2026 Hua Lian High School · Made by CHEW YEN HAN',
    'lang.switch': '中文',

    'login.heading': '🏫 Hua Lian High School J2Y Report System',
    'login.subtitle': 'Teacher Login',
    'login.username': 'Username', 'login.password': 'Password',
    'login.placeholder': 'Enter password', 'login.button': 'Login',
    'login.error': 'Invalid username or password',
    'login.reset_hint': 'Contact form teacher for password reset',
    'login.select_account': 'Select account...',

    'report.title': 'Student Feedback Entry',
    'report.hello': 'Hello', 'report.form_teacher': '(Form Teacher)',
    'report.subjects_count': 'subjects', 'report.progress': 'Progress',
    'report.mark_complete': '✅ Mark All Complete', 'report.logout': '🚪 Logout',
    'report.col_no': 'No.', 'report.col_photo': 'Photo',
    'report.col_name': 'Student Name', 'report.col_group': 'Group',
    'report.col_feedback': 'Feedback', 'report.col_status': '✅',
    'report.placeholder': 'Enter feedback...',
    'report.no_students': 'No students for this subject',
    'report.no_photo': 'No Photo', 'report.loading': 'Loading...',
    'report.load_failed': 'Failed to load', 'report.saving': 'Saving...',
    'report.saved': 'Saved', 'report.save_failed': 'Save failed',
    'report.export_csv': '📥 Export CSV',
    'report.confirm_complete': 'Mark all students as complete?',
    'report.error_operation': 'Operation failed',

    'dashboard.title': '📊 Class Report Summary',
    'dashboard.overall_pct': 'Overall Completion',
    'dashboard.overall_filled': 'Filled / Total',
    'dashboard.subject_count': 'Total Subjects',
    'dashboard.subjects_progress': '📋 Subject Progress',
    'dashboard.matrix': '📊 Full Matrix',
    'dashboard.matrix_hint': 'Scroll horizontally to view all subjects',
    'dashboard.generate_links': '🔄 Generate/Refresh Links',
    'dashboard.links_hint': 'Send each link to the corresponding parent. Each link shows only their own child.',
    'dashboard.links_placeholder': 'Click the button above to generate links',
    'dashboard.export_full': '📥 Export Full CSV',
    'dashboard.export_per_student': '📥 Export by Student',
    'dashboard.enter_report': '📝 Enter Feedback',
    'dashboard.loading': 'Loading...', 'dashboard.load_failed': 'Failed to load',
    'dashboard.teacher_col': 'Teacher', 'dashboard.student_col': 'Student',
    'dashboard.completed': 'Completed', 'dashboard.incomplete': 'Incomplete',

    'parent.loading': '⏳ Loading report...',
    'parent.title': '📋 Student Report Card',
    'parent.subjects_count': 'subjects', 'parent.col_no': '#',
    'parent.col_subject': 'Subject', 'parent.col_feedback': 'Teacher Feedback',
    'parent.col_status': 'Status', 'parent.complete': '✅ Complete',
    'parent.pending': '⏳ Pending', 'parent.no_feedback': '(No feedback yet)',
    'parent.teacher_label': 'Teacher',
    'parent.confidential': '⚠️ This report is confidential. For parents/guardians only.\nGenerated by Hua Lian High School J2Y Report System',
    'parent.error_title': '⚠️ Unable to Load Report',
    'parent.error_hint': 'Please contact the class teacher for the correct access link.',
    'parent.no_code': 'No access code provided. Please use the link from your class teacher.',
    'parent.print': '🖨️ Print',

    'group.J2Y': 'J2Y',
    'group.J2Y_name': 'J2Y 初二忠',

    'teacher.form_teacher': '👑 Form Teacher',
    'teacher.chinese_t': '📖 Chinese Teacher', 'teacher.malay_t': '📖 Malay Teacher',
    'teacher.english_t': '📖 English Teacher', 'teacher.math_t': '🔢 Math Teacher',
    'teacher.science_t': '🔬 Science Teacher', 'teacher.geography_t': '🌏 Geography Teacher',
    'teacher.history_t': '📜 History Teacher', 'teacher.computer_t': '💻 Computer Teacher',
    'teacher.pe_t': '🏃 PE Teacher', 'teacher.robotics_t': '🤖 Robotics Teacher',
    'teacher.art_t': '🎨 Art Teacher',
  }
};

function getLang() { return localStorage.getItem('report_lang') || 'zh'; }
function setLang(lang) { localStorage.setItem('report_lang', lang); }
function t(key) { return I18N[getLang()][key] || I18N['zh'][key] || key; }

function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    const text = t(key);
    if (text !== undefined && el.childNodes.length === 1 && el.childNodes[0].nodeType === 3) {
      el.textContent = text;
    }
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });
  const toggleBtn = document.getElementById('langToggle');
  if (toggleBtn) toggleBtn.textContent = t('lang.switch');
  document.title = t('site.title');
  const footer = document.getElementById('siteFooter');
  if (footer) footer.textContent = t('site.footer');
}

function toggleLang() {
  setLang(getLang() === 'zh' ? 'en' : 'zh');
  applyI18n();
  if (typeof onLangChange === 'function') onLangChange();
}

document.addEventListener('DOMContentLoaded', applyI18n);
